### ISSUE TITLE
Blank screen when loading main.dat

### ISSUE THREAD

**Issue by onlypuppy7** [FluffyFishGames/ACNHDesignPatternEditor#1]
When I (and NotRea11y) open main.dat the screen hangs there and doesn't proceed.

**Comment by FluffyFishGames** [comment]
Can you send me your complete savegame to be able to check whats wrong?

**Comment by onlypuppy7** [comment]
https://we.tl/t-CPnxZ6Wsod

**Comment by FluffyFishGames** [comment]
As we've discussed on GBATemp:
All files of the savegame needs to be present in the directory.

I will add an alert for this in the next update.
