### ISSUE TITLE
[Bug] Contextual menu doesn't show after close "choose file" window

### ISSUE THREAD

**Issue by crusardri** [FluffyFishGames/ACNHDesignPatternEditor#10]
If you click on a pattern, import, and close the "Choose file"window without select any image,  the contextual menu will not show again.

Video for reference: (I recorded only the App, i can not focus on choose file window)
https://streamable.com/falykj

**Comment by FluffyFishGames** [comment]
This bug is fixed in 0.9.3b4 and will be released with 0.9.3
