### ISSUE TITLE
[Suggestion] Add an option to Speed UP animations or remove it

### ISSUE THREAD

**Issue by crusardri** [FluffyFishGames/ACNHDesignPatternEditor#11]
The animations are too slow, and if you want to import too many patterns, it's very tedious.

It would be a good idea to add an option to remove the animations, and some dialogs like the import dialog.

I know you've worked a lot on the design of the User Interface and animations of the application, but it can be a bit annoying if you have to import many images at once.

**Comment by FluffyFishGames** [comment]
The text dialog for import has been removed and replaced by a popup for selection of QR, ACNL, ACNH or Image file. So this is basically non existant anymore in upcoming 0.9.3.
