### ISSUE TITLE
Transparency not Working

### ISSUE THREAD

**Issue by MikeDubh** [FluffyFishGames/ACNHDesignPatternEditor#12]
When I add transparency to one of my designs through the software, the areas that are transparent just show up white in the game. I know transparency is supported, but I do not know why it won’t work in my game. Please get back to me soon to fix this. Thanks.

**Comment by FluffyFishGames** [comment]
It's a known bug introduced with 0.9.3. Will be fixed for 0.9.4. But this can take ~2 weeks.

**Comment by gorkidood** [comment]
A way of fixing this is by opening the editor and in-game and removing the whites and making it transparent. That's what I have been doing.

**Comment by FluffyFishGames** [comment]
You can get the latest beta release on discord. This bug is fixed in it :)
