### ISSUE TITLE
QR Codes not working 0.9.3 bugfix/vanilla - MacOS Catalina

### ISSUE THREAD

**Issue by daitro** [FluffyFishGames/ACNHDesignPatternEditor#14]
Hello.

 I have tried a different number of Qr Codes (and both macos releases) but none of them seem to be recognised by the app.

I am not sure what I should expect when I import a QR Code but the empty squares is not changed after attempting to import it.

Among the codes that I tried. I also tried the ones from https://github.com/FluffyFishGames/ACNHDesignPatternEditor/issues/2#issue-591147777

Thank you in advance.

**Comment by FluffyFishGames** [comment]
It's a known bug caused by missing GDIPlus.dylib on your Mac. I am trying to get rid of that library for the next release. Until then you might have luck by installing Mono on your system.

**Comment by daitro** [comment]
Hi

Thank you for answering so quickly. I was just supposed to install Mono? Or there was something else needed? I only installed and no luck.

Thanks anyways. I really appreciate what you are doing! Thank you for the good work.

**Comment by FluffyFishGames** [comment]
Weird, someone on my discord had luck with that.

Then you can only wait for the next release. It will not rely on gdiplus.dylib anymore but instead is using my own graphics library + SkiaSharp.

**Comment by daitro** [comment]
I saw the discussion in discord and I did what you said there and it worked!!

**Comment by FluffyFishGames** [comment]
Nice! :)

**Comment by FluffyFishGames** [comment]
MacOSX is now supported thanks to the removal of GDIPlus and introduction of Unity Cloud Build for IL2CPP Mac build and direct texture manipulation.
