### ISSUE TITLE
Failing to scan a QR code crashes the entire program

### ISSUE THREAD

**Issue by tpanetti** [FluffyFishGames/ACNHDesignPatternEditor#15]
This is on version 0.9.4b6. Attempting to scan an image that fails to find a QR code crashes the entire program.

**Comment by FluffyFishGames** [comment]
Can you retry in 0.9.4b7 and get back to me on discord? I use discord for direct communication of bug reports in betas. Thats why betas are not shared here :) It's easier to have a conversation on discord.
