### ISSUE TITLE
Software wont work on the 1.2.0 version of animal crossing.

### ISSUE THREAD

**Issue by gorkidood** [FluffyFishGames/ACNHDesignPatternEditor#16]
When you try to open it on a new version of animal crossing 1.2.0 the software is slid all the way to the left.
![image](https://user-images.githubusercontent.com/64323198/80285241-2c506b00-872c-11ea-86f1-c532a0e748ec.png)
This is only after u load a save file.
Before u load a save file everything is good

**Comment by Kaiton121** [comment]
I have the same issue.

**Comment by gorkidood** [comment]
I guess we gotta wait for a new version of the software oh well.

**Comment by NOnooSS** [comment]
You can use beta version until a stable version show up. Link available on discord.

**Comment by gorkidood** [comment]
Where can I get a link to his discord I cant find it here

**Comment by NOnooSS** [comment]
Go on front page...

https://discord.gg/qXdxh7m
