### ISSUE TITLE
Didn't show anything when i charged my save file

### ISSUE THREAD

**Issue by arcticrow93** [FluffyFishGames/ACNHDesignPatternEditor#17]
When i charged my savefile just showed me the pink side banner at the left but let me do anything on it
I already checked the files problem and the administrator thing...
![imagen](https://user-images.githubusercontent.com/65568518/82257520-6c62d200-9915-11ea-9028-94935a3d6b5e.png)
[ACc.zip](https://github.com/FluffyFishGames/ACNHDesignPatternEditor/files/4646697/ACc.zip)

**Comment by FluffyFishGames** [comment]
Please download the latest beta on discord or wait for the incoming 0.9.4 release.
