### ISSUE TITLE
GUI not opening properly

### ISSUE THREAD

**Issue by CecilFF4** [FluffyFishGames/ACNHDesignPatternEditor#18]
Using 0.9.3p1 on Win10 x64. Tried both the x64 and x86 versions. Both lead to the result you see in the attached pic after selecting my savegame. Apparently the GUI is being drawn offset so much that it can't be used.

![error](https://user-images.githubusercontent.com/12663305/82284666-29c5e780-995f-11ea-9f3b-86a4a70f295e.png)

**Comment by FluffyFishGames** [comment]
You are using a 1.2.0 savegame with a version which doesn't support 1.2.0 savegames. Try the beta on discord. (Like stated in several other tickets with this exact same error)
