### ISSUE TITLE
Can not import a QR code correctly

### ISSUE THREAD

**Issue by PlanetesH** [FluffyFishGames/ACNHDesignPatternEditor#2]
Same question as LilGec on GBATemp:
a lot of qr codes that I try just come up blank, no design or info is loaded, just a white square. 
![1111](https://user-images.githubusercontent.com/62905135/78036671-28376480-739d-11ea-9f22-d77d293e3922.png)
Thank you for your hard work！

**Comment by FluffyFishGames** [comment]
Noted. Will fix in 0.9.2

**Comment by FluffyFishGames** [comment]
Can you by any chance add some of these QR codes in here? :)

**Comment by PlanetesH** [comment]
Sure，For instance：

![QQ截图20200331224301](https://user-images.githubusercontent.com/62905135/78040121-9847e980-73a1-11ea-880a-f4d7f8e190fd.png)
![QQ截图20200331224021](https://user-images.githubusercontent.com/62905135/78040144-9f6ef780-73a1-11ea-9bc8-dfe0e62eca51.png)
![QQ截图20200331224205](https://user-images.githubusercontent.com/62905135/78040269-c75e5b00-73a1-11ea-8303-ab0b492ed802.png)
They can all be identified but just a white square.

**Comment by PlanetesH** [comment]
And but this similar code can be perfectly identified
![QQ截图20200331225001](https://user-images.githubusercontent.com/62905135/78040668-566b7300-73a2-11ea-81bb-d2a7648f0694.png)
