### ISSUE TITLE
(MACOS) Clickable entities not opening finder or responding

### ISSUE THREAD

**Issue by Aymiie** [FluffyFishGames/ACNHDesignPatternEditor#21]
None of the options are opening anything or responding when clicked on mac os, works perfectly well within bootcamp just mac os issue it seems

**Comment by ShroomKing** [comment]
I had the same issue, turns out it's some weird codesigning/permission thing.
The app works fine when I compile it myself but when I use the provided build I can't load my savefile.

**Comment by FluffyFishGames** [comment]
Should work now in the new release :) If not, reopen the issue.
