### ISSUE TITLE
Pattern Editor Doesn't Work With Halloween Update

### ISSUE THREAD

**Issue by Le0-s** [FluffyFishGames/ACNHDesignPatternEditor#24]
Since the ACNH update on September 30th the app no longer is supported. When I try to use it I get: 
![NOT SUPPORTED](https://user-images.githubusercontent.com/72237073/94878602-849a4000-0423-11eb-9a5e-84d2aa80ddfd.png)

-version: 0.9.4p6
-When I clicked on savegame this was the response that appeared
-if you need me to send you the DxDiagtxt please let me know and I will DM it to you

**Comment by FluffyFishGames** [comment]
Version 0.9.4p7 supports game version 1.5.0
