### ISSUE TITLE
Can't choose main.dat in macOS version

### ISSUE THREAD

**Issue by Hawods** [FluffyFishGames/ACNHDesignPatternEditor#3]
<img width="793" alt="image" src="https://user-images.githubusercontent.com/4013417/78326369-c9e0d080-75ac-11ea-8373-05e7e7870b26.png">

File type pattern may be wrong.

**Comment by haydengise** [comment]
i am having the same issue

**Comment by FluffyFishGames** [comment]
Seems like specifying a complete name doesnt work with the FileChooser Plugin I use. Will be fixed in next release.

**Comment by FluffyFishGames** [comment]
Can you now select main.dat? :)

**Comment by Hawods** [comment]
@FluffyFishGames Yes, thank you. But import pro design QR code not working on macos, maybe I should submit another issue?
