### ISSUE TITLE
Design slots get locked when edited

### ISSUE THREAD

**Issue by shamppoo** [FluffyFishGames/ACNHDesignPatternEditor#30]
Hi! Thank you for this incredible tool<3 
Since 1.10.0 there was an issue that made it very hard to use though. 
When I perform any action (edit/import/export) on any design slot (whether it’s my own design or not) within the editor, then save and open it in the game, it’s locked and I can’t edit it.

The tool used to unlock all designs when I so much as load the save in it, which was extremely convenient. Now it’s doing the opposite, but only if I perform an action on the design slots.

If you’re wondering what I mean by “locked“ — it’s the 🚫 mark that prevents you from making changes to designs in the game.
Thank you again!! I can also hand you my save file if you need it.

**Comment by FluffyFishGames** [comment]
Seems to be a bug. And yea, I would like to have a savegame as I stopped playing the game a year ago. :)

**Comment by shamppoo** [comment]
Sorry for getting back to you a month after ): here’s my save file. I’ve used the designs here in several separate saves and only encountered the problem on this save.

[bolasaek.zip](https://github.com/FluffyFishGames/ACNHDesignPatternEditor/files/7223965/bolasaek.zip)

**Comment by lottehime** [comment]
Related to issue https://github.com/FluffyFishGames/ACNHDesignPatternEditor/issues/27.
Refer comments there due to issue being closed here.
