### ISSUE TITLE
2.0.1 Support?

### ISSUE THREAD

**Issue by Roll2Me** [FluffyFishGames/ACNHDesignPatternEditor#34]
I was editing some content with new DLC on 2.0.1 when it said version wasn't supported.  Hopefully this gets updated soon!  I realize last update was 9 days ago.  Thanks for the work

**Comment by FluffyFishGames** [comment]
I have a fulltime job and just can't sit here and await the next update to immediately update the tool. I am working on it already. Upload will start soon.
