### ISSUE TITLE
ANCH 2.0,.5

### ISSUE THREAD

**Issue by still1987** [FluffyFishGames/ACNHDesignPatternEditor#38]
hello can you still read the file of ACNH 2.0.5 
ACNH is updated to 2.0.5
Appreciate for your help

**Comment by MeziSTONE** [comment]
hi, I noticed that the display is truncated when the windows is on reduced display.
![image](https://user-images.githubusercontent.com/53018902/154815323-bdef4fdf-71af-4ef6-9143-e298d597e268.png)

**Comment by MeziSTONE** [comment]
hello, I noticed that the display is truncated when the windows are in minimized display.
![image](https://user-images.githubusercontent.com/53018902/154815514-d3c78af0-6b0a-4101-8e7b-75e710e471f8.png)

**Comment by FluffyFishGames** [comment]
The truncation is intended by (my poor) design :)
Updated for 2.0.6 just recently. I think I can close this.
