### ISSUE TITLE
pattern exchange not connecting

### ISSUE THREAD

**Issue by mady326** [FluffyFishGames/ACNHDesignPatternEditor#52]
![dsjfij](https://github.com/FluffyFishGames/ACNHDesignPatternEditor/assets/168288078/f689654f-ce7f-4707-8dc0-921a830944db)

**Comment by katelynnnn10** [comment]
I'm having the same problem! Nothing that I've tried has fixed it. The pattern exchange will not connect :(

**Comment by mady326** [comment]
> I'm having the same problem! Nothing that I've tried has fixed it. The pattern exchange will not connect :(

They FIX IT !! U CAN CHECK OUT ✅
