### ISSUE TITLE
I can't open the archive for 1.1.4

### ISSUE THREAD

**Issue by Yukikazi01** [FluffyFishGames/ACNHDesignPatternEditor#6]
Hello,My english not good,so I used Google translation,please don't mind.

I use 0.9.2d to open the 1.1.4 archive file, but the editing interface is not displayed.
![AC_NH_Design_Pattern_Editor_vsR9w1SHlK](https://user-images.githubusercontent.com/63298695/78674097-ab186c00-7915-11ea-8227-a8536f88849b.jpg)
As shown in the screenshot, it cannot be operated.
This is true whether or not it is opened with administrator rights.
 But the lower version of the archive can be used normally.
If you can solve it as soon as possible, thank you very much.

**Comment by FluffyFishGames** [comment]
It should work by redownloading the archive. There was a bug and I just replaced the archive. :)

**Comment by Yukikazi01** [comment]
Already solved, thanks a lot.
